services:
  v-ui:
    build: .
    image: v-ui:latest
    container_name: v-ui
    restart: always
    network_mode: "host"
    volumes:
      - ./data:/app/data
      - ./web:/app/web
    environment:
      - TZ=Asia/Shanghai
