"""rc.1: real TLS/proxy/DNS tests using the actual scoped subscription response."""
from contextlib import ExitStack
from copy import deepcopy
import json
import os
from pathlib import Path
import socket
import tempfile
import time
import unittest
from unittest.mock import patch
import yaml
from app.models import database
from app.services import routing_store
from app.services.core_manager import SingBoxAdapter
from app.services.mihomo_routing import default_routing
from app.services.routing_store import read_snapshot,save_routing
import test_subscription_tokens as grant_tests
from loopback_helpers import (certificate_files,DnsAnswers,start_udp_dns,start_doh,
    start_http_target,unused_port,http_through,query_txt,CoreProcess)


@unittest.skipUnless(os.getenv('VUI_TEST_MIHOMO') and os.getenv('VUI_TEST_CORES'), 'pinned real binaries required')
class LoopbackChainTests(unittest.TestCase):
    def setUp(self):
        grant_tests.SubscriptionTokenTests.setUp(self)
        self.stack=ExitStack(); self.addCleanup(self.stack.close)
        self.root=Path(self.stack.enter_context(tempfile.TemporaryDirectory(prefix='vui-real-chain-')))
        patch.object(routing_store,'ROUTING_FILE',self.root/'routing.json').start()
        self.ca,self.cert,self.key=certificate_files(self.root)
        self.server_port,self.proxy_port,self.dns_port=unused_port(),unused_port(),unused_port()
        self.target_port,self.requests=start_http_target(self.stack)
        self.boot=DnsAnswers('BOOTSTRAP', {'node.corp.test':'127.0.0.1'})
        self.direct=DnsAnswers('DIRECT_DNS', {'direct.example.test':'127.0.0.1','unlisted.example.test':'127.0.0.1'})
        self.proxied=DnsAnswers('PROXY_DNS')
        self.boot_port=start_udp_dns(self.stack,self.boot)
        self.direct_port=start_udp_dns(self.stack,self.direct)
        self.doh_port=start_doh(self.stack,self.proxied,self.cert,self.key)
        self.env={**os.environ,'SSL_CERT_FILE':str(self.ca),'SSL_CERT_DIR':str(self.root/'empty-roots')}
        (self.root/'empty-roots').mkdir()
        with database.SessionLocal() as db:
            row=db.get(database.Inbound,1)
            row.port=self.server_port
            row.settings={'users':[{'uuid':'11111111-1111-1111-1111-111111111111'}]}
            row.stream_settings={'tls':{'enabled':True,'server_name':'vpn.example.test',
                'certificate_path':str(self.cert),'key_path':str(self.key)}}
            db.commit()
            config=SingBoxAdapter().build_config([row])
        # Test-only fixtures: loopback listener and local deterministic server DNS.
        # Authentication/TLS inbound and all client rules remain generated by V-UI.
        config['inbounds'][0]['listen']='127.0.0.1'
        config['dns']={'servers':[{'type':'hosts','tag':'fixture','predefined':{'forced.example.test':'127.0.0.1'}}]}
        config['route']['default_domain_resolver']='fixture'
        self.server_config=self.root/'server.json'; self.server_config.write_text(json.dumps(config))
        self.server=CoreProcess(self.stack,[str(Path(os.environ['VUI_TEST_CORES'])/'sing-box'),'run','-c',str(self.server_config)],self.root/'server.log',self.env)
        settings={**default_routing(),'mode':'direct','proxy_domains':['forced.example.test'],
            'direct_domains':['direct.example.test'],
            'intranet':[{'suffix':'corp.test','nameservers':[f'udp://127.0.0.1:{self.boot_port}']}]}
        save_routing(settings,read_snapshot()['revision'])

    def exported_config(self):
        grant=self.client.post('/api/subscriptions',headers=grant_tests.HEADERS,json={
            'label':'real-chain','server':'node.corp.test','inbound_ids':[1],'formats':['mihomo.yaml']})
        self.assertEqual(grant.status_code,201,grant.text)
        with self.client.__class__(self.client.app,base_url=grant_tests.ORIGIN,client=('127.0.0.1',54002)) as public:
            response=public.get(grant.json()['paths']['mihomo.yaml'])
        self.assertEqual(response.status_code,200,response.text)
        original=yaml.safe_load(response.text)
        client=deepcopy(original)
        client['mixed-port']=self.proxy_port
        client['bind-address']='127.0.0.1'
        client['dns']['listen']=f'127.0.0.1:{self.dns_port}'
        client['dns']['use-hosts']=False; client['dns']['use-system-hosts']=False
        # Substitute only upstream endpoints; preserve rule order, DNS keys and
        # the #FORCE_PROXY selector. No public DNS or system changes are made.
        def resolvers(items):
            values=[]
            for value in items:
                if '#FORCE_PROXY' in value: values.append(f'https://127.0.0.1:{self.doh_port}/dns-query#FORCE_PROXY')
                elif value=='system': values.append(f'udp://127.0.0.1:{self.direct_port}')
                else: values.append(value)
            return list(dict.fromkeys(values))
        dns=client['dns']; dns['default-nameserver']=[f'127.0.0.1:{self.direct_port}']
        for field in ('nameserver','direct-nameserver','proxy-server-nameserver'): dns[field]=resolvers(dns[field])
        for field in ('nameserver-policy','proxy-server-nameserver-policy'):
            dns[field]={key:resolvers(values) for key,values in dns[field].items()}
        self.assertEqual(client['rules'],original['rules'])
        self.assertEqual(client['proxy-groups'],original['proxy-groups'])
        self.assertEqual(list(dns['nameserver-policy']),list(original['dns']['nameserver-policy']))
        self.assertFalse(client['proxies'][0]['skip-cert-verify'])
        self.assertNotIn('private_key',response.text)
        path=self.root/'client.yaml';path.write_text(yaml.safe_dump(client,sort_keys=False))
        return path

    def start(self, *, trust=True):
        self.server.start(self.server_port)
        path=self.exported_config()
        env=self.env.copy()
        if not trust:
            other,_,_=certificate_files(self.root,'untrusted')
            env['SSL_CERT_FILE']=str(other)
        self.client_core=CoreProcess(self.stack,[os.environ['VUI_TEST_MIHOMO'],'-d',str(self.root/'client-data'),'-f',str(path)],self.root/'client.log',env)
        self.client_core.start(self.proxy_port)
        # Wait for the actual DNS listener separately from the TCP proxy listener.
        deadline=time.monotonic()+5
        while True:
            try: query_txt(self.dns_port,'ready.example.test');break
            except (TimeoutError,OSError):
                if time.monotonic()>deadline: raise

    def assert_proxy_success(self, host):
        deadline=time.monotonic()+3
        last=None
        while time.monotonic()<deadline:
            try:
                status,data=http_through(self.proxy_port,host,self.target_port)
                last=(status,data)
                if last==(200,b'VUI-LOOPBACK-TARGET'):return
            except (OSError,TimeoutError) as exc:
                last=exc
            time.sleep(.08)
        self.fail(f'Proxy did not become usable: {last}\n'+(self.root/'client.log').read_text())

    def assert_proxy_failure(self):
        before=len(self.requests)
        try:
            status,_=http_through(self.proxy_port,'forced.example.test',self.target_port)
            self.assertGreaterEqual(status,400)
        except (OSError,TimeoutError): pass
        self.assertEqual(len(self.requests),before,'Failed proxy must not reach target through DIRECT')

    def test_real_proxy_direct_dns_and_stopped_proxy_never_falls_back(self):
        self.start()
        self.assert_proxy_success('direct.example.test')
        self.assert_proxy_success('unlisted.example.test')
        self.assert_proxy_success('forced.example.test')
        self.assertIn(b'PROXY_DNS',query_txt(self.dns_port,'dns.forced.example.test'))
        self.assertIn(b'DIRECT_DNS',query_txt(self.dns_port,'dns.direct.example.test'))
        self.assertIn(b'BOOTSTRAP',query_txt(self.dns_port,'dns.corp.test'))
        self.assertIn(('node.corp.test',1),self.boot.queries)
        self.assertNotIn(('node.corp.test',1),self.direct.queries)
        self.assertNotIn(('node.corp.test',1),self.proxied.queries)
        self.assertIn(('dns.forced.example.test',16),self.proxied.queries)
        self.assertNotIn(('dns.forced.example.test',16),self.direct.queries)
        self.server.stop()
        self.assert_proxy_success('direct.example.test')
        self.assert_proxy_failure()
        self.server.start(self.server_port)
        self.assert_proxy_success('forced.example.test')
        print('rc.1: real TLS proxy/direct paths, proxied DoH, node bootstrap DNS, stop/recovery passed')

    def test_untrusted_certificate_is_rejected_without_direct_fallback(self):
        self.start(trust=False)
        self.assert_proxy_success('direct.example.test')
        self.assert_proxy_failure()
        self.assertIn('certificate',(self.root/'client.log').read_text().lower())
        print('rc.1: untrusted TLS certificate rejected; direct traffic still works; no proxy fallback')

    def test_optional_fingerprint_and_alpn_handshake(self):
        with database.SessionLocal() as db:
            row=db.get(database.Inbound,1)
            stream=deepcopy(row.stream_settings)
            stream['tls']['alpn']=['h2','http/1.1']
            stream['_vui']={'client_fingerprint':'chrome'}
            row.stream_settings=stream;db.commit()
        config=json.loads(self.server_config.read_text())
        config['inbounds'][0]['tls']['alpn']=['h2','http/1.1']
        self.server_config.write_text(json.dumps(config))
        self.start()
        self.assert_proxy_success('forced.example.test')
        print('rc.1: Chrome fingerprint and ALPN handshake passed with certificate verification')

    def test_wrong_vless_credential_is_rejected_without_direct_fallback(self):
        with database.SessionLocal() as db:
            row=db.get(database.Inbound,1)
            row.settings={'users':[{'uuid':'22222222-2222-2222-2222-222222222222'}]}
            db.commit()
        self.start()
        self.assert_proxy_success('direct.example.test')
        self.assert_proxy_failure()
        print('rc.1: wrong VLESS credential rejected without fallback')

    def test_wrong_server_name_is_rejected_without_disabling_tls(self):
        with database.SessionLocal() as db:
            row=db.get(database.Inbound,1)
            stream=deepcopy(row.stream_settings);stream['tls']['server_name']='wrong.example.test'
            row.stream_settings=stream;db.commit()
        self.start()
        self.assert_proxy_failure()
        self.assertIn('certificate',(self.root/'client.log').read_text().lower())
        print('rc.1: wrong TLS server name rejected')

if __name__=='__main__': unittest.main()
